# Generated by Django 2.2.24 on 2021-10-11 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[(2, 'Bueno'), (1, 'Regular'), (0, 'Malo')], default=2, max_length=2)),
                ('debt_sbs', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[(0, 'Aprovado'), (1, 'Desaprovado'), (2, 'Pendiente')], default=0, max_length=2)),
                ('credit_indicator', models.IntegerField(max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.Client')),
            ],
        ),
    ]
