# Generated by Django 2.2.24 on 2021-10-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='credit_indicator',
            field=models.IntegerField(),
        ),
    ]
