# Generated by Django 2.2.24 on 2021-10-11 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_auto_20211011_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='state',
            new_name='punctuation',
        ),
    ]
